name = "curl"
description = "一个命令行http客户端"
dependencies = ["homebrew"]

[[install_tasks]]
[install_tasks.InstallTask]
installer = "brew"
name = "curl"

[[uninstall_tasks]]
[uninstall_tasks.UninstallTask]
installer = "brew"
name = "curl"

[[check_tasks]]
[check_tasks.WhichTask]
command = "curl"
