name = "wget"
description = "一个命令行下载工具"
dependencies = ["homebrew"]

[[install_tasks]]
[install_tasks.InstallTask]
installer = "brew"
name = "wget"

[[uninstall_tasks]]
[uninstall_tasks.UninstallTask]
installer = "brew"
name = "wget"

[[check_tasks]]
[check_tasks.WhichTask]
command = "wget"
